name: CI
on: [push]
jobs:
  build:
    name: lint_and_test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn lint
      - run: yarn test